version: '3.8'
services:
  app:
    volumes:
    - ./:/app
    environment:
    - DEBUG=true
    - LOG_LEVEL=DEBUG
    command:
    - uvicorn
    - e_commerce_order_management:app
    - --host
    - 0.0.0.0
    - --port
    - '8000'
    - --reload
