version: '3.8'

services:
  task-manager:
    image: task-manager:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - data:/app/data
    environment:
      - ENV=production
    networks:
      - internal_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  internal_network:
    internal: true

volumes:
  data: