version: '3.8'
networks:
  sdd-network:
    driver: bridge
services:
  task-management-system:
    build: .
    ports:
    - 8000:8000
    environment:
    - JWT_SECRET_KEY=${JWT_SECRET_KEY:-default_value}
    - SECRET_KEY=${SECRET_KEY:-default_value}
    depends_on: []
    volumes: []
    restart: unless-stopped
    networks:
    - sdd-network
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8000/health
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
    - sdd-network
