version: '3.8'
networks:
  sdd-network:
    driver: bridge
services:
  task-management-system:
    build: .
    ports:
    - 8000:8000
    environment:
    - JWT_SECRET_KEY=${JWT_SECRET_KEY:-default_value}
    - DATABASE_URL=${DATABASE_URL:-default_value}
    - SECRET_KEY=${SECRET_KEY:-default_value}
    - DATABASE_URL=postgresql://sdd_user:sdd_password@database:5432/sdd_db
    depends_on:
    - database
    volumes: []
    restart: unless-stopped
    networks:
    - sdd-network
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8000/health
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
  database:
    image: postgres:15-alpine
    environment:
    - POSTGRES_DB=sdd_db
    - POSTGRES_USER=sdd_user
    - POSTGRES_PASSWORD=sdd_password
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
    - sdd-network
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U sdd_user -d sdd_db
      interval: 10s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
    - sdd-network
volumes:
  postgres_data: {}
